# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Majurin muistelmat
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Iuwenis in Aeternum
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dolfinruud.github.io/rudinmuistelmat" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

paginate: 3 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown


author:
  name: Rudi Nikander

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.

defaults:
  - scope:
      path: "assets/numbers"
    values:
      number: true
  - scope:
      path: "assets/number_vid_thumbnails"
    values:
      number_vid_thumbnail: true



# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-paginate

languages: ["fi", "sv", "en"]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
